import React, { Component } from 'react';
import { Grid, Col, Row, Panel, Button } from 'react-bootstrap';

class Ayuda extends Component {
  constructor(){
    super();
  }
  render() {
    return(
      <Grid fluid>
          <Grid fluid style={{ marginTop: 70, maxWidth: '90%' }}>
          <p style={{textAlign: 'center'}}><strong><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>RAMA EJECUTIVA</span></strong></p>
          <p style={{textAlign: 'justify', lineHeight: '16.9pt', background: 'white', margin: '0in 0in 7.5pt 0in'}}>A la Rama Ejecutiva le corresponde ejecutar, de manera coordinada, todas las actividades administrativas que están al servicio de los intereses generales de la comunidad para el cumplimiento de los fines esenciales del Estado. Está representada por el Presidente de la República, el cual simboliza la unidad nacional, siendo el Jefe de Estado, Jefe de Gobierno y suprema autoridad administrativa.</p>
          <p style={{textAlign: 'justify', lineHeight: '16.9pt', background: 'white', margin: '0in 0in 7.5pt 0in'}}>El Gobierno Nacional está formado por el Presidente de la República, los ministros del despacho y los directores de departamentos administrativos.</p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif', background: 'white'}}>La organización territorial se asimila al concepto de ordenamiento territorial, el cual hace relación al conjunto de normas que establecen y regulan, por disposición de la Constitución, la forma como se distribuye espacialmente el poder público entre los diversos niveles político-administrativos de autoridad establecidos por la Carta Política&nbsp;</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Presidencia de la República </span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Se encuentra conformado por un sector central, el cual consta del departamento administrativo de la Presidencia de la República, que busca asistir al Presidente en su calidad de Jefe de Estado, Jefe de Gobierno y Suprema Autoridad Administrativa en el ejercicio de sus atribuciones constitucionales y legales; Y uno descentralizado, el cual está conformado por las entidades administrativas, siendo estas de dos tipos: las especiales con personería jurídica y la agencia estatal.</span></p>
          <p style={{textAlign: 'justify'}}><strong><span style={{fontFamily: '"Times New Roman",serif', color: '#222222', background: 'white'}}>Artículo 191</span></strong><span style={{fontFamily: '"Times New Roman",serif', color: '#222222', background: 'white'}}>. </span><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif', color: '#222222', background: 'white'}}>Para ser Presidente de la República se requiere ser&nbsp;<strong><em>c</em></strong><em>ol</em>ombiano&nbsp;por nacimiento, ciudadano en ejercicio y mayor de treinta años.</span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif', color: '#222222', background: 'white'}}>En caso de renuncia del presidente o del vicepresidente, se presentarán ante el senado quien decidirá si las admite.</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif', color: '#222222', background: 'white'}}>Vicepresidente de la Republica</span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif', color: 'black', background: 'white'}}>El Vicepresidente de la República será elegido por votación popular el mismo día y en la misma fórmula con el Presidente de la República. Los candidatos para la segunda votación, si la hubiere, deberán ser en cada fórmula quienes la integraron en la primera. </span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif', color: 'black', background: 'white'}}>El Vicepresidente tendrá el mismo período del Presidente y lo reemplazará en sus faltas temporales o absolutas, aun en el caso de que éstas se presenten antes de su posesión. En las faltas temporales del Presidente de la República bastará con que el Vicepresidente tome posesión del cargo en la primera oportunidad, para que pueda ejercerlo cuantas veces fuere necesario. En caso de falta absoluta del Presidente de la República, el Vicepresidente asumirá el cargo hasta el final del período. </span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif', color: 'black', background: 'white'}}>El Presidente de la República podrá confiar al Vicepresidente misiones o encargos especiales y designarlo en cualquier cargo de la rama ejecutiva. El Vicepresidente no podrá asumir funciones de Ministro Delegatario.&nbsp;</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerios </span></em></strong></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio del Interior:</span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Su naturaleza jurídica se desprende del sector central de la administración pública nacional, el cual tiene como objetivo dentro del marco de sus competencias y de la ley formular, adoptar, dirigir, coordinar y ejecutar la política pública, planes, programas y proyectos en materia de derechos humanos, derecho internacional humanitario, integración de la nación con las entidades territoriales, seguridad y convivencia ciudadana.</span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, se encuentra el sector descentralizado el cual está conformado por las entidades adscritas, siendo estas las unidades administrativas especiales y los establecimientos públicos, y en segundo lugar las entidades vinculadas. </span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Relaciones Exteriores: </span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Es el organismo rector del sector administrativo de relaciones exteriores, y su naturaleza jurídica se desprende del sector central, al cual le corresponde formular, planear, coordinar y ejecutar la política exterior de Colombia, las Relaciones internacionales y administrar el servicio exterior de la república.</span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado se encuentran las entidades adscritas.</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Hacienda y Crédito Público:</span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>su naturaleza jurídica se desprende del sector central de la administración nacional, teniendo como objetivo la definición, formulación y ejecución de la política económica del país, de los planes generales, programas y proyectos relacionados con esta, tales como la preparación de leyes, decretos y regulación en materia fiscal, tributaria, aduanera, de crédito publico, presupuestal, financiera, cambiaria, monetaria y crediticia.</span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado se encuentran dos entidades, las cuales son las adscritas, donde se encuentra el fondo que cuenta con personería jurídica, las superintendencias con personería jurídica, las unidades administrativas especiales; y las vinculadas, donde se encuentran las sociedades de economía mixta, empresa industrial y comercial del estado, las de naturaleza especial y las entidades financieras de naturaleza única. </span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Justicia y del Derecho:</span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Su naturaleza jurídica se desprende del sector central de la administración nacional, siendo su objetivo formular, adoptar, coordinar, dirigir y ejecutar la política pública en materia de ordenamiento jurídico, de defensa y seguridad jurídica, drogas, acceso a la justicia formal y alternativa, lucha contra la criminalidad, mecanismos judiciales transicionales, prevención y control de delito. Además, es el encargado de coordinar las relaciones entre la rama ejecutiva, la rama judicial, el ministerio público, los organismos de control y demás entidades públicas y privadas, para el desarrollo y consolidación de la política pública en materia de justicia y derecho.</span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado se encuentran las entidades adscritas, conformadas por los establecimientos públicos, unidades administrativas especiales y las superintendencias con personería jurídica; y vinculadas. </span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Defensa Nacional: </span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Su naturaleza jurídica se desprende del sector central de la administración nacional, tiene como objetivos primordiales la formulación y adopción de las políticas, planes generales, programas y proyectos del sector administrativo, para la defensa de la soberanía, la independencia y la integridad territorial. Además, el mantenimiento del orden constitucional y la garantía de la convivencia democrática. </span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado se encuentran las entidades adscritas, constituidas por la superintendencia con personería jurídica y establecimientos públicos de las fuerzas militares, y vinculadas, las cuales cuentan con las empresas industriales y comerciales y las sociedades de economía mixta.</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Agricultura y Desarrollo Rural:</span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Su naturaleza jurídica se desprende del sector central de la administración nacional, teniendo como objetivo promover el desarrollo rural con enfoque territorial y el fortalecimiento de la productividad y competitividad de los productos agropecuarios, para obtener un mejor aprovechamiento de los recursos naturales y, asimismo, generar empleo y un crecimiento sostenido. </span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado el sector agropecuario, pesquero y de desarrollo rural está conformado por entidades adscritas con personería jurídica, siendo estos los establecimientos públicos, unidades administrativas especiales y agencias estatales de naturaleza especial, y sin personería jurídica. Y, se encuentran las entidades vinculadas, conformadas por sociedades de economía mixta y corporaciones de participación mixta.</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Salud y Protección Social: </span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>su naturaleza jurídica se desprende del sector central de la administración nacional, y dentro del marco de sus competencias tiene como objetivo formular, adoptar, dirigir, coordinar, ejecutar y evaluar la política pública en materia de salud, salud pública y promoción social en salud. Además, cuenta con participación para formular políticas en materia de pensiones, beneficios económicos periódicos y riesgos profesionales.</span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, se encuentra el sector descentralizado, el cual se encuentra conformado por entidades adscritas, estas a su vez se conforman por superintendencias, establecimientos públicos, empresas sociales del estado y la administradora de recursos del sistema general de seguridad social en salud (ADRES).</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Trabajo: </span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>su naturaleza jurídica se desprende del sector central de la administración nacional, y como objetivo tiene la formulación y adopción de políticas, planes generales, programas y proyectos para el trabajo, dando lugar al respeto de los derechos fundamentales, las garantías de los trabajadores, el fortalecimiento, promoción y protección de las actividades de la economía solidaria y el trabajo decente.</span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado se encuentran las entidades adscritas, conformadas por superintendencias, establecimientos públicos, unidades administrativas especiales con personería jurídica; y las entidades vinculadas, las cuales se conforman por las empresas industriales y comerciales del estado.</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Minas y Energía: </span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>su naturaleza jurídica se desprende del sector central de la administración nacional, teniendo como objetivo formular, adoptar, dirigir y coordinar las políticas, planes y programas del sector de minas y energía. </span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado se encuentran las entidades adscritas, tales como las unidades administrativas especiales sin y con personería jurídica, establecimientos públicos, agencias estatales e institutos, y las entidades vinculadas, las cuales son las sociedades de economía mixta y las empresas de servicios públicos domiciliarios.</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Comercio, Industria y Turismo: </span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>su naturaleza jurídica se desprende del sector central de la administración nacional, tiene como objetivo formular, adoptar, dirigir y coordinar las políticas generales en materia de desarrollo económico y social del país, relacionadas con la competitividad, integración y desarrollo de los sectores productivos de la industria, la micro, pequeña y mediana empresa, el comercio exterior de bienes y servicios y tecnología, la promoción de inversión extranjera, el comercio interno y el turismo. Además, de ejecutar las políticas, planes generales, programas y proyectos de comercio exterior.</span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado se encuentra conformado por entidades adscritas, siendo estas las superintendencias con personería jurídica y unidades administrativas especiales con personería jurídica, y las entidades vinculadas, las cuales son las sociedades de economía mixta y las corporaciones e instituciones de investigación.</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Educación Nacional:</span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>su naturaleza jurídica se desprende del sector central de la administración nacional, tiene como objetivos establecer las políticas y los lineamientos para dotar al sector educativo de un servicio de calidad con acceso equitativo y con permanencia en el sistema, diseñar estándares que definan el nivel fundamental de calidad de la educación, garantizar y promover, por parte del estado a través de políticas públicas, el derecho y el acceso a un sistema educativo público sostenible y de calidad. Además, debe orientar la educación superior en el marco de la autonomía universitaria, velar por la calidad de la educación mediante el ejercicio de las funciones de regulación, inspección, vigilancia y evaluación.</span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado se conforma por las entidades adscritas, siendo los establecimientos públicos, y las entidades vinculadas, las cuales son las sociedades de economía mixta y las entidades de naturaleza especial.</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Ambiente y Desarrollo Sostenible:</span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>&nbsp;su naturaleza jurídica se desprende del sector central de la administración nacional, tiene como objetivo orientar y regular el ordenamiento ambiental del territorio y de definir las políticas y regulaciones a las que sujetaran la recuperación, conservación, protección, ordenamiento, manejo, uso y aprovechamiento sostenible de los recursos renovables y del ambiente de la nación, con el fin de asegurar el desarrollo sostenible. Además, tiene el deber de formular la política nacional ambiental y de recursos renovables de manera que se garantice el derecho de todas las personas a gozar de un medio ambiente sano y se proteja el patrimonio natural y la soberanía de la nación. </span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado se conforma por entidades adscritas, como los establecimientos públicos, y entidades vinculadas, las cuales son las corporaciones e instituciones de investigación. </span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Vivienda, Ciudad y Territorio</span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>&nbsp;su naturaleza jurídica se desprende del sector central de la administración nacional, tiene como objetivo formular, adoptar, dirigir, coordinar y ejecutar la política pública, planes y proyectos en materia de desarrollo territorial y urbano planificado del país, la consolidación de ciudades, con patrones de uso eficiente y sostenible del suelo, teniendo en cuenta las condiciones de acceso y financiación de vivienda y de prestación de los servicios públicos de agua potable y saneamiento básico. </span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado está conformado por las unidades administrativas especiales sin personería jurídica, entidades adscritas y entidades vinculadas. </span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Tecnologías de la Información y las Comunicaciones: </span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Su naturaleza jurídica se desprende del sector central de la administración nacional, tiene como objetivo principal diseñar, formular, adoptar y promover las políticas, planes, programas y proyectos del sector de tecnologías de la información y las comunicaciones, en correspondencia con la Constitución Política y la ley, con el fin de contribuir al desarrollo económico, social y político de la nación. Además, promover el uso y apropiación de las tecnologías de la información y las comunicaciones, entre los ciudadanos, las empresas y el gobierno.</span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado se encuentran las entidades adscritas, conformadas por unidades administrativas especiales sin y con personería jurídica, y las entidades vinculadas, conformadas por empresas industriales y comerciales del estado.</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Transporte:</span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>&nbsp;su naturaleza jurídica se desprende del sector central de la administración nacional, cuyo objetivo es la formulación y adopción de las políticas, planes, programas, proyectos y regulación económica en materia de transporte, tránsito e infraestructura de los modos de transporte carretero, marítimo, fluvial, férreo y aéreo. Además, la regulación técnica en materia de transporte y tránsito. </span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado está conformado por las entidades adscritas, las cuales son las unidades administrativas especiales, establecimientos públicos, agencia estatal y la superintendencia.</span></p>
          <p style={{textAlign: 'justify'}}><strong><em><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Ministerio de Cultura: </span></em></strong></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>su naturaleza jurídica se desprende del sector central de la administración nacional, y como objetivo principal tiene formular, coordinar, ejecutar y vigilar la política del Estado en materia cultural, deportiva, recreativa y el aprovechamiento del tiempo libre, de manera coherente con los planes de desarrollo, con los principios fundamentales contemplados en la Constitución Política y en la ley.</span></p>
          <p style={{textAlign: 'justify'}}><span style={{fontSize: '12.0pt', lineHeight: '107%', fontFamily: '"Times New Roman",serif'}}>Por otro lado, en el sector descentralizado conformado por las entidades adscritas, las cuales son establecimientos públicos.</span></p>
        </Grid>
      </Grid>
    );
  }
}
export default Ayuda;